### ISSUE TITLE
[PATCH] Fix build on systems where default lua is 5.2

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1597]
```
What version of the product are you using? On what operating system?
OS: ArchLinux
Architecture x86_64
IBus version: 1.5.1
Input method name and version: ibus-pinyin
Python version: 2.7.3
dbus version: 1.6.8
dbus-python version: 1.1.1

What steps will reproduce the problem?
1. Try to build ibus-pinyin on a system with both lua5.1 and lua5.2 installed but where
default lua is 5.2

What is the expected output? What do you see instead?
Application should be correctly, but fails with the following errors:
  CCLD     lua-ext-console
./.libs/libpylua.a(libpylua_la-lua-plugin.o): In function `lua_plugin_init':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin.c:57: undefined reference to `lua_open'
./.libs/libpylua.a(libpylua_la-lua-plugin.o): In function `ibus_engine_plugin_get_retvals':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin.c:289: undefined reference to
`lua_objlen'
./.libs/libpylua.a(libpylua_la-lua-plugin.o): In function `ibus_engine_plugin_call':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin.c:213: undefined reference to
`lua_objlen'
./.libs/libpylua.a(libpylua_la-lua-plugin-init.o): In function `luaopen_ime':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin-init.c:347: undefined reference
to `luaL_register'
./.libs/libpylua.a(libpylua_la-lua-plugin-init.o): In function `ime_register_trigger':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin-init.c:221: undefined reference
to `lua_objlen'
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin-init.c:233: undefined reference
to `lua_objlen'
./.libs/libpylua.a(libpylua_la-lua-plugin-init.o): In function `ime_join_string':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lua-plugin-init.c:91: undefined reference
to `lua_objlen'
./.libs/libpylua.a(libpylua_la-lmyoslib.o): In function `luaopen_myos':
/home/nuno/work/ibus/code/ibus-pinyin/lua/lmyoslib.c:160: undefined reference to `luaL_register'
collect2: error: ld returned 1 exit status


Please provide any additional information below.

This happens because the detection of the installed lua only checks if it's version
is greater or equal to 5.1 but not if it is less than 5.2.

Attached patch fix the problem. Applies to master

```

Original issue reported on code.google.com by `nuno.araujo@russo79.com` on 2013-01-25 18:07:49

<hr>
- _Attachment: [0001-Fix-build-on-systems-where-default-lua-is-5.2.patch](https://storage.googleapis.com/google-code-attachments/ibus/issue-1581/comment-0/0001-Fix-build-on-systems-where-default-lua-is-5.2.patch)_
