### ISSUE TITLE
1.5.32-rc1 link error in portal/ibus-portal-dbus.c with glib 2.82

### ISSUE THREAD

**Issue by tsutsui** [ibus/ibus#2734]
### Distribution and Version

NetBSD/i386 10.1 and pkgsrc-2024Q4

### Desktop Environment and Version

gtk3 3.24.43 and glib2 2.82.2

### Session Type

X11

### Application and Version

(build issue)

### IBus version

1.5.32-rc1

### Issue Description

ibus-1.5.32-rc1.tar.gz has the following changes:
```diff
--- ibus-1.5.32-beta2/portal/ibus-portal-dbus.c	2025-02-07 08:47:16.000000000 +0900
+++ ibus-1.5.32-rc1/portal/ibus-portal-dbus.c	2025-02-27 23:34:23.000000000 +0900
@@ -1564,7 +1564,11 @@
 
   GVariantBuilder builder;
   guint n;
-  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
+#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_84
+  g_variant_builder_init_static (&builder, G_VARIANT_TYPE ("a{sv}"));
+#else
+  g_variant_builder_init(&builder, G_VARIANT_TYPE ("a{sv}"));
+#endif
   if (_ibus_dbus_portal_interface_info.parent_struct.properties == NULL)
     goto out;
   for (n = 0; _ibus_dbus_portal_interface_info.parent_struct.properties[n] != NULL; n++)
```

However, `GLIB_VERSION_2_84` macro is not defined in `glib/gversionmacros.h` on glib2 2.82 and prior, so
`#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_84`
is always true and link against `g_variant_builder_init_static` fails with glib2 2.82:
```
  CC       ibus_portal-ibus-portal-dbus.o
  CC       ibus_portal-portal.o
  GEN      org.freedesktop.portal.IBus.service
ibus-portal-dbus.c: In function 'ibus_dbus_portal_skeleton_dbus_interface_get_properties':
ibus-portal-dbus.c:1568:3: warning: implicit declaration of function 'g_variant_builder_init_static'; did you mean 'g_variant_builder_init'? [-Wimplicit-function-declaration]
 1568 |   g_variant_builder_init_static (&builder, G_VARIANT_TYPE ("a{sv}"));
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   g_variant_builder_init
  CCLD     ibus-portal
ld: ibus_portal-ibus-portal-dbus.o: in function `ibus_dbus_portal_skeleton_dbus_interface_get_properties':
ibus-portal-dbus.c:(.text+0x13da): undefined reference to `g_variant_builder_init_static'
ld: ibus_portal-ibus-portal-dbus.o: in function `ibus_dbus_input_context_skeleton_dbus_interface_get_properties':
ibus-portal-dbus.c:(.text+0x1440): undefined reference to `g_variant_builder_init_static'
ld: ibus_portal-ibus-portal-dbus.o: in function `_ibus_dbus_input_context_emit_changed':
ibus-portal-dbus.c:(.text+0x390e): undefined reference to `g_variant_builder_init_static'
ld: ibus-portal-dbus.c:(.text+0x3931): undefined reference to `g_variant_builder_init_static'
ld: ibus_portal-ibus-portal-dbus.o: in function `ibus_dbus_service_skeleton_dbus_interface_get_properties':
ibus-portal-dbus.c:(.text+0x4d39): undefined reference to `g_variant_builder_init_static'
gmake[3]: *** [Makefile:664: ibus-portal] Error 1
```

It works around to remove and regenerate `ibus-1.5.32-rc1/portal/ibus-portal-dbus.[ch]`,
but it's a bit annoying that `ibus-1.5.32-rc1/portal/ibus-portal-dbus.[ch]` in release tar ball is not portable.

### Steps to Reproduce

```bash
See above.
Try to build `ibus-1.5.32-rc1/portal/ibus-portal-dbus.[ch]` in the release tar ball with glib2 2.82 or prior.
```

### Can you reproduce your problem when you restart ibus-daemon? (yes / no)

N/A (build issue)

### Do you see any errors when you run ibus-daemon with the verbose option?

N/A (build issue)

### Can you reproduce your problem with a new user account instead of the
current your account? (yes / no)

N/A (build issue)

**Comment by fujiwarat** [comment]
ibus-1.5.32-rc1.tar.gz was build in Fedora 42 with glib2-2.83.2
ibus-1.5.32-beta2.tar.gz was build in Fedora 42 with glib2-2.82.2

`GLIB_VERSION_2_84` is defined in `glib/gversionmacros.h` in glib2-2.83.2 and `ibus-portal-dbus.c` was generated by `gdbus-codegen` command.

It might be good to add `#ifdef GLIB_VERSION_2_84` in  `ibus-portal-dbus.c` but it would be the `gdbus-codegen` issue  but not ibus.
The workaround is to run `make -C portal maintainer-clean-generic` after you run `./configure` and generate `ibus-portal-dbus.c` for your distro.
