### ISSUE TITLE
ibus-hangul: setup doesn't work with ibus 1.5.x

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1604]
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...):
Architecture (i386, x86_64):
IBus version: 1.5.1
Input method name and version: ibus-hangul 1.4.2
Python version: 2.7
dbus version: 1.5.8
dbus-python version: 1.1.1


$ dpkg -s ibus|grep Version
Version: 1.5.1-1
$ dpkg -s ibus-hangul|grep Version
Version: 1.4.2-1
$ ibus-setup-hangul 
Traceback (most recent call last):
  File "/usr/share/ibus-hangul/setup/main.py", line 208, in <module>
    Setup(bus).run()
  File "/usr/share/ibus-hangul/setup/main.py", line 38, in __init__
    self.__config.connect("value-changed", self.on_value_changed, None)
AttributeError: 'NoneType' object has no attribute 'connect'
$

```

Original issue reported on code.google.com by `ryu.changwoo` on 2013-02-10 02:19:54
